version: '3.7'

services:

  web:
    image: sdkconsultoria/php-dev-serve
    links:
      - mysql
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    ports:
      - '${APP_PORT:-80}:80'
    secrets:
      - host_ssh_key
    networks:
      - servers
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=sdk_template
      - MYSQL_USER=sdk_template
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_HOST=%
    networks:
      - servers
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - servers

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - servers
secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa
networks:
  servers:
    driver: bridge
volumes:
  db-mysql:
    driver: local
